export const doseData = [
    {
        label: "O.D.",
        value: "Once"
    },
    {
        label: "B.I.D.",
        value: "Twice"
    },
    {
        label: "T.I.D.",
        value: "Thrice"
    },
    {
        label: "Q.I.D.",
        value: "Four times"
    }
]

export const intakeTimeData = [
    {
        label: "After Meal",
        value: "After Meal"
    },
    {
        label: "Before Meal",
        value: "Before Meal"
    },
]

export const medicinesData = [
    { value: "Acetaminophen", label: "Acetaminophen" },
    { value: "Albuterol", label: "Albuterol" },
    { value: "Amlodipine", label: "Amlodipine" },
    { value: "Amoxicillin", label: "Amoxicillin" },
    { value: "Aspirin", label: "Aspirin" },
    { value: "Atenolol", label: "Atenolol" },
    { value: "Atorvastatin", label: "Atorvastatin" },
    { value: "Azithromycin", label: "Azithromycin" },
    { value: "Benadryl", label: "Benadryl" },
    { value: "Ciprofloxacin", label: "Ciprofloxacin" },
    { value: "Citalopram", label: "Citalopram" },
    { value: "Clindamycin", label: "Clindamycin" },
    { value: "Clopidogrel", label: "Clopidogrel" },
    { value: "Codeine", label: "Codeine" },
    { value: "Cyclobenzaprine", label: "Cyclobenzaprine" },
    { value: "Diclofenac", label: "Diclofenac" },
    { value: "Dolo", label: "Dolo" },
    { value: "Doxycycline", label: "Doxycycline" },
    { value: "Enalapril", label: "Enalapril" },
    { value: "Escitalopram", label: "Escitalopram" },
    { value: "Fentanyl", label: "Fentanyl" },
    { value: "Fluconazole", label: "Fluconazole" },
    { value: "Fluoxetine", label: "Fluoxetine" },
    { value: "Furosemide", label: "Furosemide" },
    { value: "Gabapentin", label: "Gabapentin" },
    { value: "Hydrochlorothiazide", label: "Hydrochlorothiazide" },
    { value: "Hydrocodone", label: "Hydrocodone" },
    { value: "Ibuprofen", label: "Ibuprofen" },
    { value: "Insulin", label: "Insulin" },
    { value: "Lansoprazole", label: "Lansoprazole" },
    { value: "Lisinopril", label: "Lisinopril" },
    { value: "Loratadine", label: "Loratadine" },
    { value: "Losartan", label: "Losartan" },
    { value: "Meloxicam", label: "Meloxicam" },
    { value: "Metformin", label: "Metformin" },
    { value: "Methotrexate", label: "Methotrexate" },
    { value: "Metoprolol", label: "Metoprolol" },
    { value: "Naproxen", label: "Naproxen" },
    { value: "Omeprazole", label: "Omeprazole" },
    { value: "Oxycodone", label: "Oxycodone" },
    { value: "Pantoprazole", label: "Pantoprazole" },
    { value: "Paroxetine", label: "Paroxetine" },
    { value: "Penicillin", label: "Penicillin" },
    { value: "Phenobarbital", label: "Phenobarbital" },
    { value: "Phenytoin", label: "Phenytoin" },
    { value: "Pramipexole", label: "Pramipexole" },
    { value: "Prednisone", label: "Prednisone" },
    { value: "Pregabalin", label: "Pregabalin" },
    { value: "Propranolol", label: "Propranolol" },
    { value: "Quetiapine", label: "Quetiapine" },
    { value: "Ranitidine", label: "Ranitidine" },
    { value: "Risperidone", label: "Risperidone" },
    { value: "Rosuvastatin", label: "Rosuvastatin" },
    { value: "Sertraline", label: "Sertraline" },
    { value: "Simvastatin", label: "Simvastatin" },
    { value: "Sildenafil", label: "Sildenafil" },
    { value: "Sodium Chloride", label: "Sodium Chloride" },
    { value: "Spironolactone", label: "Spironolactone" },
    { value: "Sumatriptan", label: "Sumatriptan" },
    { value: "Tacrolimus", label: "Tacrolimus" },
    { value: "Tadalafil", label: "Tadalafil" },
    { value: "Tamsulosin", label: "Tamsulosin" },
    { value: "Temazepam", label: "Temazepam" },
    { value: "Terazosin", label: "Terazosin" },
    { value: "Tetracycline", label: "Tetracycline" },
    { value: "Thyroxine", label: "Thyroxine" },
    { value: "Tizanidine", label: "Tizanidine" },
    { value: "Topiramate", label: "Topiramate" },
    { value: "Tramadol", label: "Tramadol" },
    { value: "Trazodone", label: "Trazodone" },
    { value: "Triamterene", label: "Triamterene" },
    { value: "Trimethoprim", label: "Trimethoprim" },
    { value: "Valacyclovir", label: "Valacyclovir" },
    { value: "Valproic acid", label: "Valproic acid" },
    { value: "Valsartan", label: "Valsartan" },
    { value: "Venlafaxine", label: "Venlafaxine" },
    { value: "Verapamil", label: "Verapamil" },
    { value: "Vitamin D", label: "Vitamin D" },
    { value: "Warfarin", label: "Warfarin" },
    { value: "Zolpidem", label: "Zolpidem" },
]